### ISSUE TITLE
Chat doesn't persists 

### ISSUE THREAD

**Issue by siddxharth1** [sp9324/dsa-practice-site#12]
The chat doesn't persist when switching from the chat page to the code page and then returning to the chat page.
Can you assign this issue to me i would like to resolve this and also label this as hacktoberfest

**Comment by sp9324** [comment]
> The chat doesn't persist when switching from the chat page to the code page and then returning to the chat page. Can you assign this issue to me i would like to resolve this and also label this as hacktoberfest

Could please upload a short screen recording of this feature, please?
